### ISSUE TITLE
Wholeview Direct Logo Swap

### ISSUE THREAD

**Issue by cunning-folk** [cunning-folk/Wholeview_Medicaid#10]
I think for https://wholeview.co/wholeview-direct/ we need to swap the vertical logo for the horizontal logo. If you want to leave the vertical logo on the mobile navigation bar, that is fine.

CC: @lukemiller

Horizontal logo 4x:

![Image](https://user-images.githubusercontent.com/31627480/193879084-6b64daab-ea9b-4f49-8888-056293093158.png)

Horizontal PNG 3x:

![Image](https://user-images.githubusercontent.com/31627480/193879148-2739360c-0e01-405d-b178-b8a08a86be0c.png)

Screenshot:

![Image](https://user-images.githubusercontent.com/31627480/193879004-dcdf2318-bc8e-4322-8317-53beccfbd2d7.png)

**Comment by lukemiller** [comment]
@cunning-folk do you have an svg version for this?

**Comment by cunning-folk** [comment]
![Image](https://user-images.githubusercontent.com/31627480/193944123-1d7aa5dd-3c91-40e5-8f1e-156da971680a.svg)

@lukemiller here ya go

**Comment by cunning-folk** [comment]
@lukemiller hey there. Any idea of an ETA for this issue? Just give me a date so I can update the client. Thanks!

**Comment by lukemiller** [comment]
@cunning-folk - done :-)

https://5cbe1b4fd60bac49a83f76d8.cloud-preview.siteleaf.com/wholeview-direct/about-us/

if that looks good to you, we can go ahead and push to production

**Comment by cunning-folk** [comment]
looks great. go ahead and push. thanks!
