### ISSUE TITLE
Tech Stack list

### ISSUE THREAD

**Issue by cunning-folk** [cunning-folk/Wholeview_Medicaid#13]

**Comment by cunning-folk** [comment]
Hey there

Time for me to help Wholeview start looking for new dev help.

To find a new resource can you please provide the overall stack so they can search for a competent developer?

Thanks!

**Comment by jeremylenz** [comment]
Sure!

I'd look for a developer who has experience with

* Jekyll & Jekyll Liquid
* HTML
* CSS including SCSS
* Git
* Github
* Responsive design
* Vanilla JavaScript

Some experience with the following is helpful (but not essential):
* Ruby
* YAML
* Siteleaf
* AWS S3
* AWS Route 53
* AWS Cloudfront

I updated [README.md](https://github.com/CunningFolkDev/elevate360_website#readme) with our current tech stack and publishing flow as well.

**Comment by jeremylenz** [comment]
@cunning-folk hopefully this is what you needed? ^

**Comment by cunning-folk** [comment]
Yup! Perfect.
