### ISSUE TITLE
Homepage - Nav Section Missing

### ISSUE THREAD

**Issue by cunning-folk** [cunning-folk/Wholeview_Medicaid#5]

**Comment by cunning-folk** [comment]
I note that the newer Direct pages and navigation render correctly everywhere __except__ for the homepage. Does anyone know how to fix this?

**Comment by jeremylenz** [comment]
Looks like it's just a propagation issue. The new nav link does correctly show on http://www.wholeview.co.s3-website-us-east-1.amazonaws.com/

**Comment by cunning-folk** [comment]
I feel like the propagation should have resolved by now? Thoughts? @lukemiller
