### ISSUE TITLE
Wholeview Direct Logo Disappeared

### ISSUE THREAD

**Issue by cunning-folk** [cunning-folk/Wholeview_Medicaid#6]

**Comment by cunning-folk** [comment]
@lukemiller

Looks like the Wholeview Direct logo disappeared from the top-level navigation. 



![Image](https://user-images.githubusercontent.com/31627480/193584065-39236b1a-aeaa-4c8a-9d4e-11bf25756c72.png)

**Comment by jeremylenz** [comment]
I'm assuming you mean that when you click on Wholeview Direct in the main nav, the logo should be the Wholeview Direct logo and not the regular Wholeview logo.

✔ fixed
