### ISSUE TITLE
Fixed Height Cards

### ISSUE THREAD

**Issue by cunning-folk** [cunning-folk/Wholeview_Medicaid#7]

**Comment by cunning-folk** [comment]
Homepage at the bottom card section: Let's get these cards fixed height. @lukemiller

I think we should stay consistent sitewide with the aesthetic of the cards. Thanks!

![Image](https://user-images.githubusercontent.com/31627480/193585214-74b3de11-d4d2-4cc6-87c8-2db822e9f7c2.png)

**Comment by lukemiller** [comment]
@cunning-folk -how's this?

https://5cbe1b4fd60bac49a83f76d8.cloud-preview.siteleaf.com/wholeview-direct/

**Comment by cunning-folk** [comment]
looks good to me.
